# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TerramProcessamento
                                 A QGIS plugin
 Krigagem de dados de fertilidade
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-17
        copyright            : (C) 2023 by Igor Viana Souza
        email                : igor.souzavigor@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TerramProcessamento class from file TerramProcessamento.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .processamento_dados import TerramProcessamento
    return TerramProcessamento(iface)
